version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=demystif
      - POSTGRES_PASSWORD=gppw2023
      - POSTGRES_DB=gin-postgres
      - POSTGRES_PORT=5432
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: gin-postgres
