services:
  postgres:
    image: postgres:15
    container_name: fiber-postgres
    environment:
      - POSTGRES_USER=tr1sm0s1n
      - POSTGRES_PASSWORD=gppw2025
      - POSTGRES_DB=fiber-postgres
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: fiber-postgres
